apiVersion: v1
kind: Pod
metadata:
  name: podnginx
  labels:
    run: nginxserver
spec:
  containers:
  - name: podnginx
    image: deciocferreira/nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "0.5"
